Started with onderenmingen endpoints
TimVanOnckelen/nbbproject-backend-ap pull request #8
Opened 2023-03-07 19:58 UTC by Brdekrom

2023-03-07 19:59 UTC, winderickxeli approved these changes
Mobile approve

2023-03-09 19:31 UTC, TimVanOnckelen approved these changes
👍

2023-03-09 19:40 UTC, TimVanOnckelen commented on NBB-Project-Back-Enc/NBB.Api/Controllers/OndernemingController.cs
> +        [HttpGet("{ondernemingsnumer}")]
Typefout in ondernemingsnumer ->  ondernemingsnummer

2023-03-09 19:41 UTC, TimVanOnckelen requested changes

2023-03-09 19:41 UTC, TimVanOnckelen commented on NBB-Project-Back-Enc/NBB.Api/Controllers/OndernemingController.cs
> +        [HttpGet("{ondernemingsnumer}")]
Typefout, nummer ipv numer

2023-03-09 20:18 UTC, Brdekrom commented
typfout opgelost

2023-03-11 06:08 UTC, winderickxeli approved these changes
OK

2023-03-11 07:38 UTC, closed without merging